### ISSUE TITLE
Where is the branch for the current version 2.6.x ?

### ISSUE THREAD

**Issue by derjohn** [magnigenie-labs/restropress#3]
In the Wordpress plugin discovery I get a never version than there.

rgds,
j

**Comment by sagarseth9** [comment]
Hello @derjohn,

This repository is not maintained currently.

We will soon start updating this so that more people can help us with the development.

Regards
Nirmal

**Comment by derjohn** [comment]
I downloaded the ZIP from your website now. Alle my development is useless because I used the old version ;)

Should I make a PR with code from the 2.6.x  :) ?

**Comment by sagarseth9** [comment]
Yes, you can.

**Comment by brospars** [comment]
Is this repo up to date ? 

We're a doing french and italian translation are you interested of merging it ?
